name: Cleanup GitHub Pages Deployments

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Remove PR preview directory
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Attempting to remove directory: pr-${PR_NUMBER}"
          if [ -d "pr-${PR_NUMBER}" ]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git rm -rf "pr-${PR_NUMBER}"
            git commit -m "Clean up: Remove preview for PR #${PR_NUMBER}"
            git push
          else
            echo "Directory pr-${PR_NUMBER} not found. No cleanup needed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 