name: Deploy Flutter Web

on:
  push:
    branches: [main]
    paths:
      - 'coinbag_flutter/**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Enable web platform
        run: flutter create . --platforms=web
        working-directory: coinbag_flutter
      - name: Install dependencies
        run: flutter pub get
        working-directory: coinbag_flutter
      - name: Build web
        run: flutter build web --release --base-href /CoinBag/
        working-directory: coinbag_flutter
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coinbag_flutter/build/web
