name: Deploy Flutter Web

on:
  push:
    branches: [main]
    paths:
      - 'coinbag_flutter/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Enable web platform
        run: flutter create . --platforms=web
        working-directory: coinbag_flutter
      - name: Install dependencies
        run: flutter pub get
        working-directory: coinbag_flutter
      - name: Build web
        run: flutter build web --release
        working-directory: coinbag_flutter
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: coinbag_flutter/build/web
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
