name: Deploy Flutter Web

on:
  push:
    branches: [main]
    paths:
      - 'coinbag_flutter/**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  deployments: write

concurrency:
  group: "pages-${{ github.event.pull_request.number || 'main' }}"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.32.0

      - name: Install dependencies
        run: flutter pub get
        working-directory: coinbag_flutter

      - name: Set base href
        id: basehref
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BASEHREF=/CoinBag/pr-${{ github.event.pull_request.number }}/" >> $GITHUB_ENV
          else
            echo "BASEHREF=/CoinBag/" >> $GITHUB_ENV
          fi

      - name: Build web
        run: flutter build web --release --base-href $BASEHREF
        working-directory: coinbag_flutter

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: coinbag_flutter/build/web
          destination_dir: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || '' }}

      - name: Comment fallback preview link on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔗 Preview deployed: [Click here](https://quarezz.github.io/CoinBag/pr-${{ github.event.pull_request.number }}/)`
            })

      - name: Create Deployment with GH CLI (fixed)
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_URL: https://quarezz.github.io/CoinBag/pr-${{ github.event.pull_request.number }}/
        run: |
          echo '{
            "ref": "${{ github.event.pull_request.head.sha }}",
            "environment": "Preview",
            "auto_merge": false,
            "required_contexts": [],
            "description": "PR preview deployment",
            "transient_environment": true,
            "production_environment": false
          }' > payload.json
      
          DEPLOY_ID=$(gh api repos/${{ github.repository }}/deployments --input payload.json --jq '.id')
      
          echo "Created deployment with ID: $DEPLOY_ID"
      
          echo '{
            "state": "success",
            "environment_url": "'"$DEPLOY_URL"'",
            "description": "Preview ready at '"$DEPLOY_URL"'"
          }' > status.json
      
          gh api repos/${{ github.repository }}/deployments/$DEPLOY_ID/statuses --input status.json
          


      
        